### ISSUE TITLE
在线状态返回玩家具体情况（afk等）

### ISSUE THREAD

**Issue by sparrowhe** [SwallowMC/SouthFox#5]
需求：在线状态返回玩家具体情况（afk等）

**Comment by waterblock79** [comment]
建议再次基础上再增加：显示玩家位置（如现在在某聚落/在地狱/在末地）等

**Comment by sparrowhe** [comment]
> 建议再次基础上再增加：显示玩家位置（如现在在某聚落/在地狱/在末地）等

某聚落有难度，但是后面两者可以考虑实现
